### PR TITLE
`JsonHelper`: Raise `MissingSerializerError` if no serializer found

### LINKED ISSUE #15: Raise "Missing Serializer" error when a resource does not have a serializer
Currently `json_with` is attempting to serialize a nil object rather than raising a helpful exception.

See `serialize_json_resource` method in `json_helper.rb`: https://github.com/LaunchPadLab/rails_util/blob/8f18142b7c37fd828320d094286bbfbeacd3a362/lib/rails_util/json_helper.rb#L62

### PR DESCRIPTION
**Pull request by rkillackey**
Resolves #15 

Some additional style cleanup.

### CODE REVIEW

File: lib/rails_util/json_helper.rb [hunk 1]
```diff
@@ -59,15 +61,17 @@ def json_success(path_or_obj, message=nil, **options)
     # @param [Object] resource `ActiveRecord` resource
     # @param [Symbol=>[Integer, String, Array]] options the key-value option pairs
     # @return [Object] json resource object
+    # @raise [MissingSerializerError] if the provided resource does not have a serializer
     def serialize_json_resource(resource, **options)
-      res = ActiveModelSerializers::SerializableResource.new(resource, options[:serializer_options] || {})
-      serialized_obj = res.serializer_instance.object
-      type = options[:resource] || set_serialized_object_type(serialized_obj)
+      serializable_resource = ActiveModelSerializers::SerializableResource.new(resource, options[:serializer_options] || {})
+      raise MissingSerializerError unless serializable_resource.serializer?
```
Comment (mrjonesbot) [inline lib/rails_util/json_helper.rb]: @rkillackey 👍  LGTM 🚢
